@extends('layouts.master')
@section('title', 'الفواتير')
@section('content')
<x-ui.page-header title="الفواتير" description="متابعة فواتير الزيارات والتحصيل والمبالغ المتبقية."><a href="{{ route('invoices.service-prices') }}" class="hn-btn hn-btn-light"><i class="fe fe-settings"></i> أسعار الخدمات</a></x-ui.page-header>
<x-ui.flash />
<div class="hn-stats">
    <article class="hn-stat"><div class="hn-stat-head"><div><span class="hn-stat-label">عدد الفواتير</span><div class="hn-stat-value">{{ number_format($summary->invoice_count ?? 0) }}</div></div><span class="hn-stat-icon"><i class="fe fe-file-text"></i></span></div></article>
    <article class="hn-stat"><div class="hn-stat-head"><div><span class="hn-stat-label">إجمالي الفوترة</span><div class="hn-stat-value">{{ number_format($summary->total ?? 0, 2) }}</div></div><span class="hn-stat-icon"><i class="fe fe-dollar-sign"></i></span></div></article>
    <article class="hn-stat hn-stat-success"><div class="hn-stat-head"><div><span class="hn-stat-label">المحصل</span><div class="hn-stat-value">{{ number_format($summary->paid ?? 0, 2) }}</div></div><span class="hn-stat-icon"><i class="fe fe-check-circle"></i></span></div></article>
    <article class="hn-stat hn-stat-warning"><div class="hn-stat-head"><div><span class="hn-stat-label">المتبقي</span><div class="hn-stat-value">{{ number_format($summary->balance ?? 0, 2) }}</div></div><span class="hn-stat-icon"><i class="fe fe-clock"></i></span></div></article>
</div>
<section class="hn-panel"><div class="hn-panel-header"><div><h2 class="hn-panel-title">سجل الفواتير</h2><p class="hn-panel-subtitle">يمكن البحث برقم الفاتورة أو اسم المريض.</p></div></div><div class="hn-panel-body"><form method="GET" class="hn-filter-grid"><div><label>بحث</label><input name="search" class="form-control" value="{{ $filters['search'] ?? '' }}" placeholder="رقم الفاتورة أو المريض"></div><div><label>الحالة</label><select name="status" class="form-control"><option value="">كل الحالات</option><option value="unpaid" @selected(($filters['status'] ?? '')==='unpaid')>غير مدفوعة</option><option value="partial" @selected(($filters['status'] ?? '')==='partial')>مدفوعة جزئيًا</option><option value="paid" @selected(($filters['status'] ?? '')==='paid')>مدفوعة</option></select></div><div><label>من</label><input type="date" name="from" class="form-control" value="{{ $filters['from'] ?? '' }}"></div><div><label>إلى</label><input type="date" name="to" class="form-control" value="{{ $filters['to'] ?? '' }}"></div><div class="hn-filter-actions"><button class="hn-btn hn-btn-primary">تطبيق</button><a href="{{ route('invoices.index') }}" class="hn-btn hn-btn-light">مسح</a></div></form></div>
@if($invoices->isEmpty())<x-ui.empty title="لا توجد فواتير" description="تُنشأ الفاتورة تلقائيًا عند إكمال معاينة تحتوي خدمات." icon="fe-file-text" />@else<div class="hn-table-responsive"><table class="hn-table"><thead><tr><th>الفاتورة</th><th>المريض</th><th>العيادة</th><th>التاريخ</th><th>الإجمالي</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th><th></th></tr></thead><tbody>@foreach($invoices as $invoice)@php($status=['unpaid'=>['غير مدفوعة','hn-badge-danger'],'partial'=>['جزئية','hn-badge-warning'],'paid'=>['مدفوعة','hn-badge-success']][$invoice->status] ?? [$invoice->status,'hn-badge-pending'])<tr><td><strong>{{ $invoice->number }}</strong></td><td>{{ trim($invoice->f_name.' '.$invoice->l_name) }}</td><td>{{ $invoice->clinic_name ?: '—' }}</td><td>{{ $invoice->issued_at ? \Carbon\Carbon::parse($invoice->issued_at)->format('Y/m/d') : '—' }}</td><td>{{ number_format($invoice->total,2) }}</td><td>{{ number_format($invoice->paid,2) }}</td><td>{{ number_format($invoice->balance,2) }}</td><td><span class="hn-badge {{ $status[1] }}">{{ $status[0] }}</span></td><td><a href="{{ route('invoices.show',$invoice->id) }}" class="hn-icon-btn" title="فتح"><i class="fe fe-eye"></i></a></td></tr>@endforeach</tbody></table></div><div class="hn-pagination">{{ $invoices->links() }}</div>@endif</section>
@endsection
