@extends('layouts.master')
@section('title', 'أسعار الخدمات')
@section('content')
<x-ui.page-header title="أسعار الخدمات" description="تحديد السعر الافتراضي الذي يُنسخ إلى الفاتورة عند إنهاء المعاينة."><a href="{{ route('invoices.index') }}" class="hn-btn hn-btn-light">الفواتير</a></x-ui.page-header>
<x-ui.flash />
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="hn-panel"><div class="hn-panel-body"><form method="GET" class="hn-filter-grid"><div><label>العيادة</label><select name="clinic" class="form-control"><option value="">كل العيادات</option>@foreach($clinics as $clinic)<option value="{{ $clinic->id }}" @selected($clinicId==$clinic->id)>{{ $clinic->name_ar }}</option>@endforeach</select></div><div class="hn-filter-actions"><button class="hn-btn hn-btn-primary">عرض</button><a href="{{ route('invoices.service-prices') }}" class="hn-btn hn-btn-light">مسح</a></div></form></div></section>
<form method="POST" action="{{ route('invoices.service-prices.update') }}">@csrf @method('PUT')<section class="hn-panel"><div class="hn-panel-header"><div><h2 class="hn-panel-title">قائمة الخدمات</h2><p class="hn-panel-subtitle">تعديل السعر لا يغير الفواتير السابقة.</p></div><button class="hn-btn hn-btn-primary"><i class="fe fe-save"></i> حفظ الأسعار</button></div>@if($services->isEmpty())<x-ui.empty title="لا توجد خدمات" icon="fe-list" />@else<div class="hn-table-responsive"><table class="hn-table"><thead><tr><th>رمز الخدمة</th><th>الخدمة</th><th>رقم العيادة</th><th>السعر</th></tr></thead><tbody>@foreach($services as $service)<tr><td>{{ $service->code }}</td><td><strong>{{ $service->name_ar }}</strong></td><td>#{{ $service->clinic }}</td><td><input type="number" step="0.01" min="0" name="prices[{{ $service->id }}]" class="form-control" value="{{ number_format((float)$service->price,2,'.','') }}" required></td></tr>@endforeach</tbody></table></div><div class="hn-pagination">{{ $services->links() }}</div>@endif</section></form>
@endsection
