@extends('layouts.master')
@section('title', 'الفاتورة '.$invoice->number)
@section('content')
<x-ui.page-header :title="'الفاتورة '.$invoice->number" description="تفاصيل الخدمات والمدفوعات وحالة التحصيل."><a href="{{ route('invoices.pdf',$invoice) }}" class="hn-btn hn-btn-light"><i class="fe fe-download"></i> PDF</a><a href="{{ route('invoices.index') }}" class="hn-btn hn-btn-light">الفواتير</a></x-ui.page-header>
<x-ui.flash />
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="hn-consultation-summary"><div><small>المريض</small><strong>{{ trim(($patient->f_name ?? '').' '.($patient->l_name ?? '')) }}</strong></div><div><small>العيادة</small><strong>{{ $clinic->name_ar ?? '—' }}</strong></div><div><small>رقم الزيارة</small><strong>#{{ $invoice->visit_id }}</strong></div><div><small>تاريخ الإصدار</small><strong>{{ optional($invoice->issued_at)->format('Y/m/d H:i') }}</strong></div></section>
<form method="POST" action="{{ route('invoices.update',$invoice) }}">@csrf @method('PUT')<section class="hn-panel"><div class="hn-panel-header"><div><h2 class="hn-panel-title">بنود الفاتورة</h2><p class="hn-panel-subtitle">الأسعار هنا نسخة مالية ثابتة ولا تتأثر بتغيير سعر الخدمة لاحقًا.</p></div></div><div class="hn-table-responsive"><table class="hn-table"><thead><tr><th>الخدمة</th><th>الكمية</th><th>سعر الوحدة</th><th>الإجمالي</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $item->description }}</td><td><input type="number" step="0.01" min="0.01" class="form-control" name="items[{{ $item->id }}][quantity]" value="{{ $item->quantity }}"></td><td><input type="number" step="0.01" min="0" class="form-control" name="items[{{ $item->id }}][unit_price]" value="{{ $item->unit_price }}"></td><td>{{ number_format($item->total,2) }}</td></tr>@endforeach</tbody></table></div><div class="hn-panel-body hn-form-grid"><div class="form-group"><label>الحسم</label><input type="number" step="0.01" min="0" name="discount" class="form-control" value="{{ $invoice->discount }}"></div><div class="form-group"><label>الضريبة</label><input type="number" step="0.01" min="0" name="tax" class="form-control" value="{{ $invoice->tax }}"></div><div class="form-group"><label>تاريخ الاستحقاق</label><input type="date" name="due_at" class="form-control" value="{{ optional($invoice->due_at)->format('Y-m-d') }}"></div><div class="form-group"><label>ملاحظات</label><textarea name="notes" class="form-control">{{ $invoice->notes }}</textarea></div></div><div class="hn-panel-body"><button class="hn-btn hn-btn-primary">تحديث وحساب الفاتورة</button></div></section></form>
<div class="hn-stats"><article class="hn-stat"><div class="hn-stat-value">{{ number_format($invoice->total,2) }}</div><div class="hn-stat-label">الإجمالي</div></article><article class="hn-stat hn-stat-success"><div class="hn-stat-value">{{ number_format($invoice->paid,2) }}</div><div class="hn-stat-label">المدفوع</div></article><article class="hn-stat hn-stat-warning"><div class="hn-stat-value">{{ number_format($invoice->balance,2) }}</div><div class="hn-stat-label">المتبقي</div></article></div>
@if($invoice->balance > 0)<section class="hn-panel"><div class="hn-panel-header"><div><h2 class="hn-panel-title">تسجيل دفعة</h2><p class="hn-panel-subtitle">يُمنع تسجيل مبلغ أكبر من المتبقي.</p></div></div><div class="hn-panel-body"><form method="POST" action="{{ route('invoices.payments.store',$invoice) }}" class="hn-form-grid">@csrf<div class="form-group"><label>المبلغ</label><input type="number" step="0.01" min="0.01" max="{{ $invoice->balance }}" name="amount" class="form-control" required></div><div class="form-group"><label>طريقة الدفع</label><select name="method" class="form-control"><option value="cash">نقدي</option><option value="card">بطاقة</option><option value="transfer">تحويل</option></select></div><div class="form-group"><label>المرجع</label><input name="reference" class="form-control"></div><div class="form-group"><label>ملاحظات</label><input name="notes" class="form-control"></div><div><button class="hn-btn hn-btn-primary">تسجيل الدفعة</button></div></form></div></section>@endif
<section class="hn-panel"><div class="hn-panel-header"><div><h2 class="hn-panel-title">سجل الدفعات</h2></div></div>@if($invoice->payments->isEmpty())<x-ui.empty title="لا توجد دفعات" icon="fe-credit-card" />@else<div class="hn-table-responsive"><table class="hn-table"><thead><tr><th>التاريخ</th><th>المبلغ</th><th>الطريقة</th><th>المرجع</th></tr></thead><tbody>@foreach($invoice->payments as $payment)<tr><td>{{ optional($payment->paid_at)->format('Y/m/d H:i') }}</td><td>{{ number_format($payment->amount,2) }}</td><td>{{ ['cash'=>'نقدي','card'=>'بطاقة','transfer'=>'تحويل'][$payment->method] ?? $payment->method }}</td><td>{{ $payment->reference ?: '—' }}</td></tr>@endforeach</tbody></table></div>@endif</section>
@endsection
